apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
  namespace: bestbuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
        - name: store-front
          image: youssufalgonquin/bestbuy-store-front:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: store-front
  namespace: bestbuy
spec:
  selector:
    app: store-front
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
